### PR TITLE
[Beta] Adding block tags doc

### PR DESCRIPTION
**Pull request by JaminQuimby**

### CODE REVIEW

**Comment by JaminQuimby** [comment]
Fixes SirLich/bedrock-wiki#189

**Comment by SirLich** [comment]
@JaminQuimby thanks for the PR!

Do you think `Block Type` is the best name for this concept? I'm not doing too much with blocks at the moment, so I'm not sure. Somebody also mentioned "block tags" as the name for this concept?

Speaking of which: I think this would benefit with 1-2 sentences at the top, saying what these are. Doesn't need to be expansive, just something small.

Also, is this Beta? If so, it should be marked as [Beta] in the title. See other examples on the wiki.

If you want to collaborate further, join the discord: https://discord.gg/XjV87YN

Sorry for the rambling review. If you don't get back to me by tomorrow I will probably just merge it in, and then fix any issues as needed.

**Comment by JaminQuimby** [comment]
Will fix.

**Comment by sermah** [comment]
@JaminQuimby where did you get info about this thing? Nobody knows anything about it. How to use these tags?

**Pull request merged**
